### ISSUE TITLE
Wanderer's Coda display bug

### ISSUE THREAD

**Issue by 4i7** [SupineSnail/SupineSnail.JobGaugeAdjustments#2]
![image](https://user-images.githubusercontent.com/3959289/161327913-25d5df6b-d584-46a6-8306-49bb42d6c60c.png)

**Comment by SupineSnail** [comment]
This should be easy to fix, just probably didn’t notice there were multiple elements to move at once. When I get some time I’ll take a look

**Comment by SupineSnail** [comment]
This should be fixed in 1.0.3, though my bard is not high enough to fully test it (I tested via manually manipulating the UI to show the elements). Please let me know if it doesn't work when it comes out.

**Comment by SupineSnail** [comment]
Fix merged into plugins, should show up after plugins rebuild: https://github.com/goatcorp/DalamudPlugins/commit/cd15d1bf64db10c2c7e218076bd31bbab2d32f2a
